name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go
    - name: Set up SQLite
      run:  sudo apt-get install sqlite3

    - name: Build
      run:  script/cibuild

    - name: Set up FPM
      run:  |
        sudo apt-get install ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm

    - name: Build artifacts
      run:  |
        export GOPATH="$PWD/.gopath"
        cd .gopath/src/github.com/github/orchestrator
        ./build.sh

        mkdir -p /tmp/packages
        mv /tmp/orchestrator-release/*.deb /tmp/packages

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: /tmp/packages
